#!/usr/bin/env bash
#Author: Jason Hrabi
#Adds the specified proxy into Docker
#Based upon documentation found here: https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

function usage()
{
   echo "Shell script to inject proxy values into the Docker service daemon"
   echo ""
   echo "Usage: nimbus-docker-proxy COMMAND [OPTIONS]"
   echo -e ""
   echo -e "Commands:"
   echo -e "  add      Adds the specified proxy to the Docker service daemon."
   echo -e "           ex. nimbus-docker-proxy add http://www.myproxy.com"
   echo -e "  remove   Removes all proxy settings from the Docker service daemon"
   echo -e "  status   Shows the current Docker service proxy configuration"
}

if [[ $1 == "" ]]; then
    usage
    exit 0
  fi

while [[ "$1" != "" ]]; do
  PARAM=$1
  VALUE=$2

  case $PARAM in
    help)
      usage
      exit 0
      ;;
    add)
      if [[ -z $VALUE ]]; then
        echo "Error: No proxy value provided to add to Docker service daemon"
        exit 1;
      fi
      ACTION=$PARAM
      HTTP_PROXY_VALUE=$VALUE
      break
      ;;
    remove | status)
      ACTION=$PARAM
      break
      ;;
    *)
      echo "Invalid agument passed: $1"
      usage
      exit 1
  esac
done

if [ $ACTION  == "add" ]; then
  if [ "$EUID" -ne 0 ]; then
     echo "Please run as root or with sudo access"
     exit 1
  fi

  if [ ! -d /etc/systemd/system/docker.service.d ]; then
    sudo mkdir -p /etc/systemd/system/docker.service.d
  fi

   echo "[Service]" > /etc/systemd/system/docker.service.d/http-proxy.conf
   echo "Environment=HTTP_PROXY=${HTTP_PROXY_VALUE}" >> /etc/systemd/system/docker.service.d/http-proxy.conf
fi

if [ $ACTION  == "remove" ]; then
  if [ "$EUID" -ne 0 ]; then
     echo "Please run as root or with sudo access"
     exit 1
  fi
  if [ -f /etc/systemd/system/docker.service.d/http-proxy.conf ]; then
     rm /etc/systemd/system/docker.service.d/http-proxy.conf
  fi
fi

if [ $ACTION != "status" ]; then
  systemctl daemon-reload
  systemctl restart docker
fi

systemctl show --property=Environment docker