- name: Set Hostname to nimbusserver
  hostname:
    name: nimbusserver

- name: Disable (mask) automatic updates
  systemd:
    name: packagekit.service
    masked: yes

- name: Stop and disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: Disable SELinux
  selinux:
    state: disabled

- name: Update all installed packages
  dnf:
    name: '*'
    state: latest
    exclude:
      - ansible
      - docker-ce
      - google-chrome

- name: Install nux-dextop for Exfat Utilities
  dnf:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
    state: present

- name: Install Nimbus YUM packages
  dnf:
    name:
    - maven
    - git
    - gcc-c++
    - java-1.8.0-openjdk-devel
    - epel-release
    - rpm-build
    - zlib.i686
    - libstdc++.i686
    - python36-devel
    - python3-pip
    - kernel-devel # For NV
    - telnet
    - dos2unix     # For processing scripts
    - exfat-utils
    - fuse-exfat
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - jq

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install python modules
  pip:
    name:
    - psutil  # Used by dconf module
    - docker  # Used by docker_network module

