- name: Set Hostname to nimbusserver
  hostname:
    name: nimbusserver

- name: Disable (mask) automatic updates
  systemd:
    name: packagekit.service
    masked: yes
  
- name: Stop and disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: Disable SELinux
  selinux:
    state: disabled

- name: Update all installed packages
  yum:
    name: '*'
    state: latest
    exclude:
      - ansible
      - docker-ce

- name: Install nux-dextop for Exfat Utilities
  yum:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
    state: present

- name: Install Nimbus YUM packages
  yum:
    name:
    - maven
    - git
    - gcc-c++
    - java-1.8.0-openjdk-devel
    - epel-release
    - rpm-build
    - zlib.i686
    - libstdc++.i686
    - python-devel
    - python-pip
    - kernel-devel # For NV
    - telnet
    - dos2unix
    - exfat-utils
    - fuse-exfat
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - jq

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install python modules
  pip:
    name: 
    - psutil  # Used by dconf module
    - docker  # Used by docker_network module

# URLLIB3 FIX
# urllib3 is available in both pip and yum package managers
# packages installed with both package managers use these dependencies
# pip is able to cope with this, yum is not, so re-install here with yum
- name: urllib3 fix - remove from pip
  pip:
    name: urllib3
    state: absent

- name: urllib3 fix - install with yum
  yum:
    name: python-urllib3