- name: Install Gnome Desktop and Graphical Tools
  apt:
    name:
      - ubuntu-gnome-desktop
      - gnome-session
      - gdm3
      - xrdp
      - filezilla
      - gnome-tweaks
      - firefox
      - open-vm-tools-desktop

- name: Disable initial setup process
  service:
    name: "{{ item }}"
    masked: true
  loop:
  - gnome-initial-setup
  - gnome-initial-setup-first-login

##
## Firefox setup
##

- name: Create firefox directories
  file:
    state: directory
    path: "{{ firefox_install_dir }}/policies"
    mode: 0755
    owner: root
    group: root

- name: Copy firefox files to VM
  copy:
    src: "firefox/{{ item.file }}"
    dest: "{{ firefox_install_dir }}/{{ item.dest }}"
    mode: 0644
  loop: # If a directory, destination path should end with a forward slash /
    - { "file": "local-settings.js", "dest": "pref/" }
    - { "file": "mozilla.cfg", "dest": "" }
    - { "file": "FT.FirefoxAgent@microfocus.com.xpi", "dest": "extension/" }

- name: Download latest Firefox policies file from githubusercontent
  get_url:
    url: https://raw.githubusercontent.com/admpresales/nimbus-commons/master/firefox/policies.json
    dest: "{{ firefox_install_dir }}/policies/policies.json"
    mode: 0644
    owner: root
    group: root

- name: Configure xrdp services
  systemd:
    name: xrdp
    state: started
    enabled: true

##
## Chrome Setup
##

- name: Install google chrome
  apt:
    deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

- name: Create Google Chrome directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/opt/chrome/policies/managed
    - /etc/opt/chrome/policies/recommended
    - /opt/google/chrome/extensions
    - /opt/google/chrome/archive

- name: Copy master preferences file for Chrome into Chrome
  copy:
    remote_src: true
    src: "chrome/master_preferences"
    dest: /opt/google/chrome/master_preferences

- name: Copy ChromeDriver installer to system
  copy:
    remote_src: true
    src: "chrome/chromedriver-install.pl"
    dest: "/tmp/"

- name: Run ChromeDriver installer
  command: perl /tmp/chromedriver-install.pl

#Chrome GPO for setting browser settings as expected
- name: "Set Chrome GPO Policies"
  copy:
    content: "{{ item.content }}"
    dest: /etc/opt/chrome/policies/{{ item.type }}/{{ item.name }}.json
  loop:
    - { "name": "passwordmanager", "type": "recommended", "content": "{{ chrome_password_manager_policy }}" }
    - { "name": "metricreporting", "type": "managed", "content": "{{ chrome_metric_reporting_policy }}" }
    - { "name": "popup", "type": "managed", "content": "{{ chrome_popup_policy }}" }
    - { "name": "defaultbrowser", "type": "managed", "content": "{{ chrome_default_browser_policy }}" }
    - { "name": "newtab", "type": "recommended", "content": "{{ chrome_newtab_policy }}" }
    - { "name": "sync", "type": "recommended", "content": "{{ chrome_sync_policy }}" }

- name: Get UFT Extension for Chrome
  uri:
    url: https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&x=id%3D{{ uft_extension_id }}%26installsource%3Dondemand%26uc&acceptformat=crx2,crx3
    dest: /opt/google/chrome/archive/uft.crx
    status_code: 200,304

- name: Create plugin details for UFT Extension for Chrome
  copy:
    content: "{{ uft_extension_details }}"
    dest: /opt/google/chrome/extensions/{{ uft_extension_id }}.json

- name: Added silent debugging flag to Chrome launcher
  replace:
    path: /usr/share/applications/google-chrome.desktop
    regexp: '^Exec=\/usr\/bin\/google-chrome-stable %U'
    replace: 'Exec=/usr/bin/google-chrome-stable --password-store=basic %U --silent-debugger-extension-api'
    backup: yes

##
## Nimbus Scripts
##

- name: Create nimbus script directory
  file:
    path: /opt/nimbus/scripts
    state: directory
    mode: 0755
    owner: root
    group: "{{ admin_group }}"

- name: Copy desktop script into nimbus scripts
  copy:
    remote_src: true
    src: "trustdesktop.sh"
    dest: /opt/nimbus/scripts/trustdesktop.sh
    mode: 0755