- name: Install Gnome Desktop
  yum:
    name: "@^GNOME Desktop"
- name: Install Graphical Administration Tools
  yum:
    name: "@Graphical Administration Tools"
- name: Disable initial-setup-graphical.service
  service: name=initial-setup-graphical enabled=no state=stopped
- name: Create link for gnome desktop
  file:
    src: /lib/systemd/system/runlevel5.target
    dest: /etc/systemd/system/default.target
    state: link
    force: true

- name: Install nux-dextop for Exfat Utilities
  yum:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
    state: present
- name: Install xrdp
  yum:
    name: xrdp
- name: Configure xrdp services
  systemd:
    name: xrdp
    state: started
    enabled: true
- name: Change Maximum Sessions to 1 in sesman.ini for xrdp
  replace:
    path: /etc/xrdp/sesman.ini
    regexp: '^(.*)MaxSessions(.*)$'
    replace: 'MaxSessions=5'
    backup: yes



- name: Configure Google Chrome yum repository
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
- name: Install Google Chrome
  yum:
    name: google-chrome-stable
- name: Create managed policies directory for chrome
  file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: 0755
- name: Create recommended policies directory for chrome
  file:
    path: /etc/opt/chrome/policies/recommended
    state: directory
    mode: 0755
- name: Create external extensions directory for chrome
  file:
    path: /opt/google/chrome/extensions
    state: directory
    mode: 0755
- name: Create archive directory for extensions
  file:
    path: /opt/google/chrome/archive
    state: directory
    mode: 0755
- name: Copy master preferences file for Chrome into Chrome
  copy:
    remote_src: true
    src: "chrome/master_preferences"
    dest: /opt/google/chrome/master_preferences

#Chrome GPO for setting browser settings as expected
- name: Copy password manager policy into Chrome recommended policies
  copy: content="{{ chrome_password_manager_policy }}" dest=/etc/opt/chrome/policies/recommended/passwordmanager.json
- name: Copy metric usage policy into Chrome managed policies
  copy: content="{{ chrome_metric_reporting_policy }}" dest=/etc/opt/chrome/policies/managed/metricreporting.json
- name: Copy popup policy into Chrome managed policies
  copy: content="{{ chrome_popup_policy }}" dest=/etc/opt/chrome/policies/managed/popup.json
- name: Copy default browser policy into Chrome managed policies
  copy: content="{{ chrome_default_browser_policy }}" dest=/etc/opt/chrome/policies/managed/defaultbrowser.json
- name: Copy new tab policy into Chrome recommended policies
  copy: content="{{ chrome_newtab_policy }}" dest=/etc/opt/chrome/policies/recommended/newtab.json
- name: Copy sync policy into Chrome recommended policies
  copy: content="{{ chrome_sync_policy }}" dest=/etc/opt/chrome/policies/recommended/sync.json
- name: Get UFT Extension for Chrome
  uri:
    url: https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&x=id%3D{{ uft_extension_id }}%26installsource%3Dondemand%26uc
    dest: /opt/google/chrome/archive/uft.crx
    status_code: 200,304
- name: Create plugin details for UFT Extension for Chrome
  copy: content="{{ uft_extension_details }}" dest=/opt/google/chrome/extensions/{{ uft_extension_id }}.json
- name: Copy Chrome Bookmarks to archive
  copy:
    src: "chrome/chrome-bookmarks.html"
    dest: /opt/google/chrome/archive/chrome-bookmarks.html
    mode: 0755
    owner: demo
- name: Added silent debugging flag to Chrome launcher
  replace:
    path: /usr/share/applications/google-chrome.desktop
    regexp: '^Exec=\/usr\/bin\/google-chrome-stable %U'
    replace: 'Exec=/usr/bin/google-chrome-stable --password-store=basic %U --silent-debugger-extension-api'
    backup: yes
- name: Copy Chrome Launcher to Desktop
  copy:
    src: /usr/share/applications/google-chrome.desktop
    dest: /home/demo/Desktop
    mode: 0755
    owner: demo
- name: Remove user's existing chrome settings to update bookmarks
  file:
    path: /home/demo/.config/google-chrome
    state: absent
#
- name: Install filezilla
  yum:
    name: filezilla
#
- name: Copy local-settings to Firefox default directory
  copy:
    src: "firefox/local-settings.js"
    dest: /usr/lib64/firefox/defaults/pref
    mode: 0644
- name: Copy mozilla.cfg to Firefox install directory
  copy:
    src: "firefox/mozilla.cfg"
    dest: /usr/lib64/firefox/mozilla.cfg
    mode: 0644
- name: Copy policies to Firefox install directory
  copy:
    src: "firefox/policies.json"
    dest: "{{ firefox_install_dir }}/distribution/policies.json"
    mode: 0644
- name: Copy LeanFT extension to Firefox extensions directory
  copy:
    src: "firefox/FT.FirefoxAgent@microfocus.com.xpi"
    dest: "{{ firefox_install_dir }}/distribution/extensions/FT.FirefoxAgent@microfocus.com.xpi"
#

- name: Setup automatic login for demo
  lineinfile:
    line: "AutomaticLogin=demo"
    path: /etc/gdm/custom.conf
    insertafter: '^\[daemon\]'
    state: present

- name: Enable automatic login
  lineinfile:
    line: "AutomaticLoginEnable=True"
    path: /etc/gdm/custom.conf
    insertafter: '^AutomaticLogin=demo'
    state: present

- name: Copy desktop script into nimbus scripts
  copy:
    remote_src: true
    src: "trustdesktop.sh"
    dest: /opt/nimbus/scripts/trustdesktop.sh
    mode: 0755