- name: Install Gnome Desktop and Graphical Tools
  yum:
    name:
      - "@^GNOME Desktop"
      - "@Graphical Administration Tools"
      - xrdp

- name: Disable initial-setup-graphical.service
  service:
    name: initial-setup-graphical
    enabled: no
    state: stopped

- name: Create link for gnome desktop
  file:
    src: /lib/systemd/system/runlevel5.target
    dest: /etc/systemd/system/default.target
    state: link
    force: true

- name: Configure xrdp services
  systemd:
    name: xrdp
    state: started
    enabled: true

- name: Configure Google Chrome yum repository
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Install Google Chrome
  yum:
    name: google-chrome-stable

- name: Create Google Chrome directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/opt/chrome/policies/managed
    - /etc/opt/chrome/policies/recommended
    - /opt/google/chrome/extensions
    - /opt/google/chrome/archive

- name: Copy master preferences file for Chrome into Chrome
  copy:
    remote_src: true
    src: "chrome/master_preferences"
    dest: /opt/google/chrome/master_preferences

#Chrome GPO for setting browser settings as expected
- name: "Set Chrome GPO Policies"
  copy:
    content: "{{ item.content }}"
    dest: /etc/opt/chrome/policies/{{ item.type }}/{{ item.name }}.json
  loop:
    - { "name": "passwordmanager", "type": "recommended", "content": "{{ chrome_password_manager_policy }}" }
    - { "name": "metricreporting", "type": "managed", "content": "{{ chrome_metric_reporting_policy }}" }
    - { "name": "popup", "type": "managed", "content": "{{ chrome_popup_policy }}" }
    - { "name": "defaultbrowser", "type": "managed", "content": "{{ chrome_default_browser_policy }}" }
    - { "name": "newtab", "type": "recommended", "content": "{{ chrome_newtab_policy }}" }
    - { "name": "sync", "type": "recommended", "content": "{{ chrome_sync_policy }}" }

- name: Get UFT Extension for Chrome
  uri:
    url: https://clients2.google.com/service/update2/crx?response=redirect&prodversion=49.0&x=id%3D{{ uft_extension_id }}%26installsource%3Dondemand%26uc
    dest: /opt/google/chrome/archive/uft.crx
    status_code: 200,304

- name: Create plugin details for UFT Extension for Chrome
  copy:
    content: "{{ uft_extension_details }}"
    dest: /opt/google/chrome/extensions/{{ uft_extension_id }}.json

- name: Added silent debugging flag to Chrome launcher
  replace:
    path: /usr/share/applications/google-chrome.desktop
    regexp: '^Exec=\/usr\/bin\/google-chrome-stable %U'
    replace: 'Exec=/usr/bin/google-chrome-stable --password-store=basic %U --silent-debugger-extension-api'
    backup: yes

- name: Install filezilla
  yum:
    name: filezilla

- name: Copy firefox files to VM
  copy:
    src: "firefox/{{ item.file }}"
    dest: "{{ firefox_install_dir }}/{{ item.dest }}"
    mode: 0644
  loop:
    - { "file": "local-settings.js", "dest": "defaults/pref" }
    - { "file": "mozilla.cfg", "dest": "mozilla.cfg" }
    - { "file": "policies.json", "dest": "distribution/policies.json" }
    - { "file": "FT.FirefoxAgent@microfocus.com.xpi", "dest": "distribution/extensions/FT.FirefoxAgent@microfocus.com.xpi" }

- name: Create nimbus script directory
  file:
    path: /opt/nimbus/scripts
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Copy desktop script into nimbus scripts
  copy:
    remote_src: true
    src: "trustdesktop.sh"
    dest: /opt/nimbus/scripts/trustdesktop.sh
    mode: 0755