# HOSTS SETUP
- name: Download standard nimbus hosts file
  get_url:
    url: "https://raw.githubusercontent.com/admpresales/nimbus-commons/master/hosts"
    dest: /etc/hosts

- name: Use local address for nimbusserver
  lineinfile:
      path: /etc/hosts
      state: present
      backrefs: true
      regexp: "^\\s*\\d+\\.\\d+\\.\\d+\\.\\d+(\\s+nimbusserver.*)$"
      line: "172.50.0.1 \\1"

- name: Install Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Install Ubuntu Docker repo
  template:
    src:  docker/docker.list
    dest: /etc/apt/sources.list.d/docker.list
    mode: 0644
    newline_sequence: '\n'

# INSTALL DOCKER
- name: Install Docker Community Edition
  apt:
    update_cache: true
    name:
    - pass
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add link for docker-compose to path
  file:
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link

- name: Enable docker over TCP
  lineinfile:
    path: '/lib/systemd/system/docker.socket'
    line: ListenStream=2375
    insertafter: '\[Socket\]'

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes

# NETWORK SETUP
- name: Create Docker network demo-net
  docker_network:
    name: demo-net
    appends: true
    ipam_config:
      - subnet: '172.50.0.0/16'
        gateway: 172.50.0.1

# INSTALL FROM GITHUB
# docker-credentials-pass, docker-app, nimbusapp
- name: Get Latest release info for docker-credential-helps
  uri:
    url: https://api.github.com/repos/docker/docker-credential-helpers/releases
    return_content: true
  register: dockercredentials_json_reponse

- name: "Download releases from Github: docker-app-linux, nimbusapp"
  unarchive:
    src: "{{ item }}"
    dest: "{{ nimbus_install_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755

  loop:
    - https://github.com/admpresales/nimbusapp/releases/latest/download/nimbusapp.tar.gz
    - https://github.com/docker/app/releases/download/{{ dockerapp_tag }}/docker-app-linux.tar.gz
# - https://github.com/docker/docker-credential-helpers/releases/download/{{ helper_version }}/docker-credential-pass-{{ helper_version }}-amd64.tar.gz

- name: Download docker-credential-pass
  get_url:
    url: "https://github.com/docker/docker-credential-helpers/releases/download/{{ helper_version }}/docker-credential-pass-{{ helper_version }}.linux-amd64"
    dest: "{{ nimbus_install_dir }}/docker-credential-pass"
    owner: root
    group: docker
    mode: 0554
  vars:
    helper_version: "{{ dockercredentials_json_reponse.json[0].tag_name }}"

- name: Rename docker-app binary and set group ownership to docker
  copy:
    remote_src: true
    src: "{{ nimbus_install_dir }}/docker-app-linux"
    dest: "{{ nimbus_install_dir }}/docker-app"
    group: docker
    mode: 0775
