# HOSTS SETUP
- name: Add nimbusserver to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{item}}'
  loop:
    - 172.50.0.1  nimbusserver nimbusserver.aos.com
    - 172.40.0.1  nimbusclient

# INSTALL PASS
- name: Download password-store
  unarchive:
    src: "https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz"
    dest: "/tmp"
    remote_src: yes

- name: Install password-store
  make:
    chdir: "/tmp/password-store-1.7.3"
    target: "install"
  become: true

- name: Cleanup password-store install files
  file:
    path: "/tmp/password-store-1.7.3"
    state: "absent"

- name: Configure Docker Community Edition yum repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

# INSTALL DOCKER
- name: Install Docker Community Edition
  yum:
    name: docker-ce-19.03.8

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

# INSTALL DOCKER COMPOSE
- name: Install Python3
  yum:
    name:
      - python3
      - python3-pip

- name: Update pip-3
  pip:
    name: pip
    version: latest
    executable: pip-3

- name: Install Docker python packages
  pip:
    name: docker-compose==1.25.4
    executable: pip-3
    exclude: urllib3

# NETWORK SETUP
- name: Create Docker network demo-net
  docker_network:
    name: demo-net
    appends: true
    ipam_config:
      - subnet: '172.50.0.0/16'
        gateway: 172.50.0.1

# INSTALL FROM GITHUB
# docker-credentials-pass, docker-app, nimbusapp
- name: Get Latest release info for docker-credential-helps
  uri:
    url: https://api.github.com/repos/docker/docker-credential-helpers/releases
    return_content: true
  register: dockercredentials_json_reponse

- name: "Download releases from Github: docker-credential-pass, docker-app-linux, nimbusapp"
  unarchive:
    src: "{{item}}"
    dest: "{{nimbus_install_dir}}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  vars:
    helper_version: "{{dockercredentials_json_reponse.json[0].tag_name}}"
  loop:
    - https://github.com/docker/docker-credential-helpers/releases/download/{{helper_version}}/docker-credential-pass-{{helper_version}}-amd64.tar.gz
    - https://github.com/admpresales/nimbusapp/releases/latest/download/nimbusapp.tar.gz
    - https://github.com/docker/app/releases/download/{{dockerapp_tag}}/docker-app-linux.tar.gz

- name: Rename docker-app binary and set group ownership to docker
  copy:
    remote_src: true
    src: "{{nimbus_install_dir}}/docker-app-linux"
    dest: "{{nimbus_install_dir}}/docker-app"
    group: docker
    mode: 0775

# INSTALL SCRIPTS
- name: Install nimbus scripts to /usr/local/bin
  copy:
    src: "scripts/{{item}}"
    dest: "{{nimbus_install_dir}}"
    mode: 0755
  loop: "{{nimbus_scripts}}"

- name: Run dos2unix on nimbus scripts in /usr/local/bin
  shell: "dos2unix {{nimbus_install_dir}}/{{item}}"
  loop: "{{nimbus_scripts}}"