- hosts: localhost
  remote_user: root
  become: yes

  vars:
    uft_extension_details: { "external_crx": "/opt/google/chrome/archive/uft.crx", "external_version": "15.0.2.3122"}
    uft_extension_id: kglbdihdcnciobeihioplammnkknjmbd
    uft_firefox_extension_id: ec8030f7-c20a-464f-9b0e-13a3a9e97384
    chrome_password_manager_policy: { "PasswordManagerEnabled" : false }
    chrome_metric_reporting_policy: { "MetricsReportingEnabled" : false }
    chrome_popup_policy: { "DefaultPopupsSetting" : 1 }
    chrome_default_browser_policy: { "DefaultBrowserSettingEnabled" : false }
    chrome_newtab_policy: { "NewTabPageLocation" : "about:blank" }
    chrome_sync_policy: { "SyncDisabled" : true }

    docker_credstore: { "credsStore": "pass" }
    pubkey: "{{ lookup('file', 'ssh/id_rsa.pub') }}"
    # firefox_install_dir: /usr/lib64/firefox
    firefox_install_dir: /home/demo/snap/firefox/current/usr/lib/firefox
    dockerapp_tag: "v0.6.0"
    nimbus_scripts: [ "nimbus-docker-proxy", "nimbus-ftp-load", "sap-vpn" ]

    nimbus_install_dir: "/usr/local/bin"
    nimbus_user: "demo"
    nimbus_group: "{{ nimbus_user }}"

    # file permissions
    admin_user: "root"
    admin_group: "{{ admin_user }}"

    pass_version: 1.7.3
    docker_version: 20.10.2
    compose_version: 1.27.4

    softether_download: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.38-9760-rtm/softether-vpnclient-v4.38-9760-rtm-2021.08.17-linux-x64-64bit.tar.gz

    registration_code: '' # MF-TE Registration code, to be injected at build time

  tasks:
    - include_tasks: "base.yml"
    - include_tasks: "docker.yml"
    - include_tasks: "sap-vpn.yml"
    - include_tasks: "desktop.yml"
    - include_tasks: "demo-user.yml"

# # The docker_network module fails if an incompatible gssapi version is installed
# # gssapi is not required for the plugin to function, so remove it
# # https://github.com/paramiko/paramiko/issues/1069#issuecomment-352459767
# - name: Remove python-gssapi
#   yum:
#     name: python-gssapi
#     state: removed