- name: Install python modules
  pip:
    name:
    - psutil  # Used by dconf module
    - docker  # Used by docker_network module

- name: Download and extract SoftEther source
  unarchive:
    remote_src: true
    src: "{{ softether_download }}"
    dest: '/opt'

- name: Build SoftEther
  make:
    chdir: /opt/vpnclient
